export const FETCH_NEAREST_TOURNAMENTS = 'FETCH_NEAREST_TOURNAMENTS';
export const FETCH_TOURNAMENTS = 'FETCH_TOURNAMENTS';
export const GET_CURRENT_TOURNAMENT = 'GET_CURRENT_TOURNAMENT';
export const SEND_ENTER_TOURNAMENT_REQUEST = 'SEND_ENTER_TOURNAMENT_REQUEST';
export const FETCH_TOURNAMENT_TEAMS = 'FETCH_TOURNAMENT_TEAMS';
